#标题
#swagger.title=game
#swagger.description=The play was very interesting
#swagger.version=版本
#swagger.license=许可证
#swagger.licenseUrl=许可证URL
#swagger.termsOfServiceUrl= 服务条款URL
#swagger.contact.name=维护人
#swagger.contact.url=维护人URL
#swagger.contact.email=维护人email
#swagger.base-package=com.game
#swagger.base-path=需要处理的基础URL规则，默认：/**
swagger:
  title: game
  description: The play was very interesting
  base-package: com.game

spring:
  datasource:
    master:
      url: jdbc:mysql://localhost:3306/ddbb
      username: root
      password: root
      driverClassName: com.mysql.jdbc.Driver
    slave:
      url: jdbc:mysql://localhost:3306/ddbb
      username: root
      password: root
      driverClassName: com.mysql.jdbc.Driver
